<?php

declare(strict_types=1);

namespace CrawlTool\Generator;

use CrawlTool\Utils\Logger;

/**
 * Generates router.php with $requick array and switch statements
 * This allows URLs to work without 404 errors
 */
class RouterGenerator
{
    private Logger $logger;

    public function __construct(Logger $logger)
    {
        $this->logger = $logger;
    }

    /**
     * Generate router.php based on specs
     */
    public function generate(string $outputDir, array $specs): void
    {
        $routerDir = $outputDir . '/libraries';
        if (!is_dir($routerDir)) {
            mkdir($routerDir, 0777, true);
        }

        $content = $this->buildRouterContent($specs);
        file_put_contents("$routerDir/router.php", $content);
        $this->logger->info("Generated router.php");
    }

    private function buildRouterContent(array $specs): string
    {
        $php = "<?php\n";
        $php .= "/* Generated Router - Auto-generated by CrawlTool */\n\n";

        // Standard header checks
        $php .= "/* Check HTTP */\n";
        $php .= "\$func->checkHTTP(\$http, \$config['arrayDomainSSL'], \$configBase, \$configUrl);\n\n";
        $php .= "/* Validate URL */\n";
        $php .= "\$func->checkUrl(\$config['website']['index']);\n\n";
        $php .= "/* Check login */\n";
        $php .= "\$func->checkLoginMember();\n\n";

        // Mobile detect
        $php .= "/* Mobile detect */\n";
        $php .= "\$deviceType = (\$detect->isMobile() || \$detect->isTablet()) ? 'mobile' : 'computer';\n";
        $php .= "define('TEMPLATE', './templates/');\n\n";

        // Router setup
        $php .= "/* Router */\n";
        $php .= "\$router->setBasePath(\$config['database']['url']);\n";
        $php .= "\$router->map('GET|POST', '', 'index', 'home');\n";
        $php .= "\$router->map('GET|POST', 'index.php', 'index', 'index');\n";
        $php .= "\$router->map('GET|POST', 'sitemap.xml', 'sitemap', 'sitemap');\n";
        $php .= "\$router->map('GET|POST', '[a:com]', 'allpage', 'show');\n";
        $php .= "\$router->map('GET', THUMBS . '/[i:w]x[i:h]x[i:z]/[**:src]', function (\$w, \$h, \$z, \$src) {\n";
        $php .= "    global \$func;\n";
        $php .= "    \$func->createThumb(\$w, \$h, \$z, \$src, null, THUMBS);\n";
        $php .= "}, 'thumb');\n\n";

        // Router match
        $php .= "/* Router match */\n";
        $php .= "\$match = \$router->match();\n\n";
        $php .= "/* Router check */\n";
        $php .= "if (is_array(\$match)) {\n";
        $php .= "    if (is_callable(\$match['target'])) {\n";
        $php .= "        call_user_func_array(\$match['target'], \$match['params']);\n";
        $php .= "    } else {\n";
        $php .= "        \$com = (!empty(\$match['params']['com'])) ? htmlspecialchars(\$match['params']['com']) : htmlspecialchars(\$match['target']);\n";
        $php .= "        \$getPage = !empty(\$_GET['p']) ? htmlspecialchars(\$_GET['p']) : 1;\n";
        $php .= "    }\n";
        $php .= "} else {\n";
        $php .= "    header('HTTP/1.0 404 Not Found', true, 404);\n";
        $php .= "    include(\"404.php\");\n";
        $php .= "    exit;\n";
        $php .= "}\n\n";

        // Setting
        $php .= "/* Setting */\n";
        $php .= "\$sqlCache = \"select * from #_setting\";\n";
        $php .= "\$setting = \$cache->get(\$sqlCache, null, 'fetch', 7200);\n";
        $php .= "\$optsetting = (!empty(\$setting['options'])) ? json_decode(\$setting['options'], true) : null;\n\n";

        // Lang
        $php .= "/* Lang */\n";
        $php .= "if (!empty(\$match['params']['lang'])) \$_SESSION['lang'] = \$match['params']['lang'];\n";
        $php .= "else if (empty(\$_SESSION['lang']) && empty(\$match['params']['lang'])) \$_SESSION['lang'] = 'vi';\n";
        $php .= "\$lang = \$_SESSION['lang'];\n";
        $php .= "\$sluglang = 'slugvi';\n";
        $php .= "\$seolang = \"vi\";\n\n";

        // Generate $requick array
        $php .= $this->buildRequickArray($specs);

        // Generate switch statements
        $php .= $this->buildSwitchStatement($specs);

        // Include sources
        $php .= "/* Require datas for all page */\n";
        $php .= "require_once SOURCES . \"allpage.php\";\n\n";
        $php .= "/* Include sources */\n";
        $php .= "if (!empty(\$source)) {\n";
        $php .= "    include SOURCES . \$source . \".php\";\n";
        $php .= "}\n\n";
        $php .= "/* Check template */\n";
        $php .= "if (empty(\$template)) {\n";
        $php .= "    header('HTTP/1.0 404 Not Found', true, 404);\n";
        $php .= "    include(\"404.php\");\n";
        $php .= "    exit();\n";
        $php .= "}\n";

        return $php;
    }

    /**
     * Build $requick array for URL optimization
     */
    private function buildRequickArray(array $specs): string
    {
        $php = "/* Tối ưu link - Auto generated */\n";
        $php .= "\$requick = array(\n";

        foreach ($specs as $nametype => $spec) {
            $base = $spec['base'] ?? 'other';
            if ($base === 'other') continue;

            $source = $this->getSourceFromBase($base);
            $table = $this->getTableFromBase($base);

            // Main table
            $php .= "    array(\"tbl\" => \"$table\", \"field\" => \"id\", \"source\" => \"$source\", \"com\" => \"$nametype\", \"type\" => \"$nametype\", \"menu\" => true),\n";

            // Category tables for news/product
            if ($base === 'product' || $base === 'news') {
                $php .= "    array(\"tbl\" => \"{$table}_list\", \"field\" => \"idl\", \"source\" => \"$source\", \"com\" => \"$nametype\", \"type\" => \"$nametype\"),\n";
                $php .= "    array(\"tbl\" => \"{$table}_cat\", \"field\" => \"idc\", \"source\" => \"$source\", \"com\" => \"$nametype\", \"type\" => \"$nametype\"),\n";
                $php .= "    array(\"tbl\" => \"{$table}_item\", \"field\" => \"idi\", \"source\" => \"$source\", \"com\" => \"$nametype\", \"type\" => \"$nametype\"),\n";
                $php .= "    array(\"tbl\" => \"{$table}_sub\", \"field\" => \"ids\", \"source\" => \"$source\", \"com\" => \"$nametype\", \"type\" => \"$nametype\"),\n";
            }
        }

        // Add contact
        $php .= "    array(\"tbl\" => \"\", \"field\" => \"id\", \"source\" => \"\", \"com\" => \"lien-he\", \"type\" => \"\", \"menu\" => true),\n";

        $php .= ");\n\n";

        // Find data logic
        $php .= "/* Find data */\n";
        $php .= "if (!empty(\$com) && !in_array(\$com, ['tim-kiem', 'account', 'sitemap'])) {\n";
        $php .= "    foreach (\$requick as \$k => \$v) {\n";
        $php .= "        \$urlTbl = (!empty(\$v['tbl'])) ? \$v['tbl'] : '';\n";
        $php .= "        \$urlType = (!empty(\$v['type'])) ? \$v['type'] : '';\n";
        $php .= "        \$urlField = (!empty(\$v['field'])) ? \$v['field'] : '';\n";
        $php .= "        \$urlCom = (!empty(\$v['com'])) ? \$v['com'] : '';\n\n";
        $php .= "        if (!empty(\$urlTbl) && !in_array(\$urlTbl, ['static', 'photo'])) {\n";
        $php .= "            \$row = \$d->rawQueryOne(\"select id from #_\$urlTbl where \$sluglang = ? and type = ? and find_in_set('hienthi',status) limit 0,1\", array(\$com, \$urlType));\n\n";
        $php .= "            if (!empty(\$row['id'])) {\n";
        $php .= "                \$_GET[\$urlField] = \$row['id'];\n";
        $php .= "                \$com = \$urlCom;\n";
        $php .= "                break;\n";
        $php .= "            }\n";
        $php .= "        }\n";
        $php .= "    }\n";
        $php .= "}\n\n";

        return $php;
    }

    /**
     * Build switch statement for route handling
     */
    private function buildSwitchStatement(array $specs): string
    {
        $php = "/* Switch coms */\n";
        $php .= "switch (\$com) {\n";

        foreach ($specs as $nametype => $spec) {
            $base = $spec['base'] ?? 'other';
            if ($base === 'other') continue;

            $source = $this->getSourceFromBase($base);
            $template = $this->getTemplateFromBase($base, $spec);
            $titleConst = $this->getTitleConstant($nametype);

            $php .= "    case '$nametype':\n";
            $php .= "        \$source = \"$source\";\n";

            if ($base === 'static') {
                $php .= "        \$template = \"static/static\";\n";
            } else {
                $php .= "        \$template = isset(\$_GET['id']) ? \"{$source}/{$source}_detail\" : \"{$source}/{$source}\";\n";
            }

            $php .= "        \$seo->set('type', isset(\$_GET['id']) ? \"article\" : \"object\");\n";
            $php .= "        \$type = \$com;\n";
            $php .= "        \$titleMain = $titleConst;\n";
            $php .= "        break;\n\n";
        }

        // Contact page
        $php .= "    case 'lien-he':\n";
        $php .= "        \$source = \"contact\";\n";
        $php .= "        \$template = \"contact/contact\";\n";
        $php .= "        \$seo->set('type', 'object');\n";
        $php .= "        \$titleMain = lienhe;\n";
        $php .= "        break;\n\n";

        // Index page
        $php .= "    case '':\n";
        $php .= "    case 'index':\n";
        $php .= "        \$source = \"index\";\n";
        $php .= "        \$template = \"index/index\";\n";
        $php .= "        \$seo->set('type', 'website');\n";
        $php .= "        break;\n\n";

        // Default 404
        $php .= "    default:\n";
        $php .= "        header('HTTP/1.0 404 Not Found', true, 404);\n";
        $php .= "        include(\"404.php\");\n";
        $php .= "        exit();\n";
        $php .= "}\n\n";

        return $php;
    }

    private function getSourceFromBase(string $base): string
    {
        return match ($base) {
            'product' => 'product',
            'news' => 'news',
            'static' => 'static',
            default => 'allpage'
        };
    }

    private function getTableFromBase(string $base): string
    {
        return match ($base) {
            'product' => 'product',
            'news' => 'news',
            'static' => 'static',
            default => ''
        };
    }

    private function getTemplateFromBase(string $base, array $spec): string
    {
        $hasDetail = $spec['has_detail'] ?? false;
        return match ($base) {
            'product' => $hasDetail ? 'product/product_detail' : 'product/product',
            'news' => $hasDetail ? 'news/news_detail' : 'news/news',
            'static' => 'static/static',
            default => 'allpage/allpage'
        };
    }

    private function getTitleConstant(string $nametype): string
    {
        // Convert slug to constant name (e.g., 'tin-tuc' -> 'tintuc')
        $const = str_replace('-', '', $nametype);
        return $const;
    }
}
